from sqlalchemy.orm import Session

from .models import Product

PRODUCT_SEED_DATA = [
    {
        "id": 1,
        "name": "Cloud Mesh Crop Top",
        "brand": "SHEIN MIX",
        "description": "Breathable mesh crop top with contrast piping and stretch comfort.",
        "price": 18.99,
        "original_price": 29.99,
        "rating": 4.7,
        "reviews": 842,
        "category": "Women",
        "badge": "Flash Sale",
        "is_new": True,
        "colors": ["Sky Blue", "White", "Coral"],
        "sizes": ["XS", "S", "M", "L"],
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 2,
        "name": "Street Cargo Joggers",
        "brand": "Urban Thread",
        "description": "High-waist cargo joggers with utility pockets and tapered ankle.",
        "price": 34.5,
        "original_price": 49.0,
        "rating": 4.8,
        "reviews": 1092,
        "category": "Women",
        "badge": "Top Rated",
        "is_new": False,
        "colors": ["Sand", "Black"],
        "sizes": ["S", "M", "L", "XL"],
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 3,
        "name": "Minimal Oversized Shirt",
        "brand": "North Point",
        "description": "Crisp oversized shirt designed for layered street looks.",
        "price": 26.0,
        "original_price": 38.0,
        "rating": 4.5,
        "reviews": 426,
        "category": "Men",
        "badge": "Daily Pick",
        "is_new": True,
        "colors": ["Sky", "Ivory", "Navy"],
        "sizes": ["M", "L", "XL"],
        "image": "https://images.unsplash.com/photo-1527719327859-c6ce80353573?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 4,
        "name": "Retro Wave Sneakers",
        "brand": "MonoRun",
        "description": "Chunky retro sneakers with cushioned sole and breathable upper.",
        "price": 52.0,
        "original_price": 72.0,
        "rating": 4.9,
        "reviews": 2210,
        "category": "Men",
        "badge": "Best Seller",
        "is_new": False,
        "colors": ["Orange", "White", "Sky Blue"],
        "sizes": ["40", "41", "42", "43", "44"],
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 5,
        "name": "Crystal Mini Shoulder Bag",
        "brand": "Luma",
        "description": "Compact shoulder bag with metallic clasp and detachable strap.",
        "price": 21.75,
        "original_price": 35.0,
        "rating": 4.6,
        "reviews": 680,
        "category": "Accessories",
        "badge": "New",
        "is_new": True,
        "colors": ["Sky Blue", "Silver", "Orange"],
        "sizes": ["One Size"],
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 6,
        "name": "Pearl Layer Necklace Set",
        "brand": "Mira",
        "description": "Layered necklace set with pearls and geometric pendants.",
        "price": 12.99,
        "original_price": 22.0,
        "rating": 4.4,
        "reviews": 512,
        "category": "Accessories",
        "badge": "Under $15",
        "is_new": False,
        "colors": ["Gold", "Silver"],
        "sizes": ["One Size"],
        "image": "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 7,
        "name": "Glow Hydration Serum",
        "brand": "Skin Orbit",
        "description": "Lightweight serum with niacinamide and hyaluronic acid.",
        "price": 16.5,
        "original_price": 28.0,
        "rating": 4.7,
        "reviews": 1338,
        "category": "Beauty",
        "badge": "Viral",
        "is_new": True,
        "colors": ["N/A"],
        "sizes": ["30 ml"],
        "image": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 8,
        "name": "Velvet Matte Lip Set",
        "brand": "Skin Orbit",
        "description": "Four-piece matte lip kit with long-wear pigments.",
        "price": 19.25,
        "original_price": 33.0,
        "rating": 4.3,
        "reviews": 409,
        "category": "Beauty",
        "badge": "Limited",
        "is_new": False,
        "colors": ["Rose", "Coral", "Brick", "Nude"],
        "sizes": ["4 pcs"],
        "image": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 9,
        "name": "Scandi Glow Table Lamp",
        "brand": "Casa Ease",
        "description": "Warm LED table lamp with soft matte finish.",
        "price": 31.5,
        "original_price": 45.0,
        "rating": 4.8,
        "reviews": 288,
        "category": "Home",
        "badge": "Editor Pick",
        "is_new": False,
        "colors": ["Cream", "Sky Blue", "Black"],
        "sizes": ["One Size"],
        "image": "https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 10,
        "name": "Soft Grid Bedding Set",
        "brand": "Casa Ease",
        "description": "Breathable cotton bedding set with modern grid print.",
        "price": 44.99,
        "original_price": 64.99,
        "rating": 4.6,
        "reviews": 540,
        "category": "Home",
        "badge": "Bundle",
        "is_new": True,
        "colors": ["Sky Blue", "White"],
        "sizes": ["Queen", "King"],
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 11,
        "name": "Aero Knit Polo",
        "brand": "North Point",
        "description": "Slim-fit knit polo with textured weave.",
        "price": 27.0,
        "original_price": 41.0,
        "rating": 4.5,
        "reviews": 367,
        "category": "Men",
        "badge": "Fresh",
        "is_new": True,
        "colors": ["Sky Blue", "Charcoal"],
        "sizes": ["S", "M", "L", "XL"],
        "image": "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": 12,
        "name": "Pleated Tennis Skirt",
        "brand": "SHEIN MIX",
        "description": "High-rise pleated skirt with built-in shorts.",
        "price": 23.75,
        "original_price": 35.0,
        "rating": 4.7,
        "reviews": 995,
        "category": "Women",
        "badge": "Hot",
        "is_new": False,
        "colors": ["White", "Sky Blue", "Black"],
        "sizes": ["XS", "S", "M", "L"],
        "image": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    },
]

HERO_BANNERS = [
    {
        "id": 1,
        "title": "Spring Drop 2026",
        "subtitle": "Up to 65% OFF selected looks",
        "cta": "Shop New Arrivals",
    },
    {
        "id": 2,
        "title": "Skyline Streetwear",
        "subtitle": "Mix orange heat with cool blue layers",
        "cta": "Explore Collection",
    },
    {
        "id": 3,
        "title": "Beauty Flash Event",
        "subtitle": "Buy 2 get 1 free on trending skincare",
        "cta": "Glow Now",
    },
]


def seed_products_if_needed(db: Session) -> None:
    has_products = db.query(Product.id).first()
    if has_products:
        return

    for product in PRODUCT_SEED_DATA:
        db.add(Product(**product))
    db.commit()
